import Head from 'next/head'
import Image from 'next/image'
import CreatePoll from '../components/CreatePoll/CreatePoll'
import NavBar from '../components/NavBar/NavBar'
import ViewPoll from '../components/ViewPoll/ViewPoll'
import { Provider } from 'react-redux';
import { store } from '../app/store'

export default function Home() {
  return (
    <Provider store={store}>

      <div>
        <Head>
          <title>Real Time Poll</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />
        <CreatePoll />
        <ViewPoll />
        
      </div>
    </Provider>
  )
}
